import './globals.css'
import type { Metadata } from 'next'
import NextSessionProvider from "@/Providers/NextSessionProvider";
import toast, { Toaster } from 'react-hot-toast';
import Header from './components/Headers/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <head>
      </head>
      <html lang="en" className='flex flex-col'>
        <body>
            <NextSessionProvider>
              <Toaster toastOptions={{
                className: '',
                style: {
                  border: '1px solid #ff6446',
                  padding: '5px 10px',
                  color: '#ff6446',
                  fontWeight: '500'
                },
                iconTheme: {
                  primary: '#ff6446',
                  secondary: '#FFFAEE',
                },
              }} />
              <Header />
              {children}
            </NextSessionProvider>
        </body>
      </html>
    </>
  )
}
