import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from './components/Navbar'
import NextAuthSessionProvider from '@/Providers/sessionProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <head>
      </head>
      <html lang="en" className='flex flex-col'>
        <body>
          <NextAuthSessionProvider>
            <Navbar />
            {children}
          </NextAuthSessionProvider>
        </body>
      </html>
    </>
  )
}
